name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential cmake libsqlite3-dev libgtest-dev

    - name: Create build directory
      run: mkdir build

    - name: Configure
      run: |
        cd build
        cmake -DCMAKE_BUILD_TYPE=Debug ..

    - name: Build
      run: |
        cd build
        make

    - name: Run tests
      run: |
        cd build
        ctest --output-on-failure

    - name: Generate coverage report
      run: |
        cd build
        lcov --capture --directory . --output-file coverage.info
        lcov --remove coverage.info '/usr/*' --output-file coverage.info
        lcov --list coverage.info

    - name: Upload coverage report
      uses: codecov/codecov-action@v2
      with:
        file: ./build/coverage.info
        fail_ci_if_error: true 